{% set name = "txl-notebook-editor" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_notebook_editor-{{ version }}.tar.gz
  sha256: 28f456682b47ed1a8dd20523df0321b461d6931885d887e696562b697d9baf96

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - pycrdt >=0.8.11,<0.9.0
    - jupyter_ydoc >=2.0.0,<3.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_notebook_editor

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/notebook_editor
  summary: TXL plugin for a notebook editor
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/notebook_editor
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
